# Generated by Django 2.1.3 on 2019-03-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190330_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
