# Generated by Django 2.1.3 on 2019-03-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_company_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='company'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customer'),
        ),
    ]
