# Generated by Django 2.1.3 on 2019-04-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20190402_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='barcode',
        ),
    ]
