# Generated by Django 2.1.3 on 2019-04-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20190404_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='region',
        ),
    ]
